export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT';

export const REQUEST_ROBOS_PENDDING = 'REQUEST_ROBOS_PENDDING';
export const REQUEST_ROBOS_SUCCESS = 'REQUEST_ROBOS_SUCCESS';
export const REQUEST_ROBOS_FAILED = 'REQUEST_ROBOS_FAILED';